<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<AssemblyVersion>0.1.0</AssemblyVersion>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>$(NoWarn);IDE0130</NoWarn>
	</PropertyGroup>

    <ItemGroup>
		<PackageReference Include="App.Metrics.AspNetCore.Endpoints" Version="4.3.0" />
		<PackageReference Include="App.Metrics.AspNetCore.Hosting" Version="4.3.0" />
		<PackageReference Include="App.Metrics.Formatters.Prometheus" Version="4.3.0" />
		<PackageReference Include="Dapper" Version="2.1.79" />
		
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
        <PackageReference Include="Netezos" Version="3.0.3" />
        <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
        <PackageReference Include="SauceControl.Blake2Fast" Version="2.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Xtzkt.Data\Xtzkt.Data.csproj" />
        <ProjectReference Include="..\Xtzkt.Indexers.Common\Xtzkt.Indexers.Common.csproj" />
        <ProjectReference Include="..\Xtzkt.Utils\Xtzkt.Utils.csproj" />
    </ItemGroup>

	<ItemGroup>
		<None Update="Protocols\Handlers\Proto05\Activation\airdropped.contracts">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Protocols\Handlers\Proto13\Activation\emptied.contracts">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Protocols\Handlers\Proto13\Activation\patched.contracts">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Protocols\Handlers\Proto15\Activation\patched.contracts">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
