<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyVersion>0.1.0</AssemblyVersion>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Netezos" Version="3.0.3" />
		<PackageReference Include="SauceControl.Blake2Fast" Version="2.0.0" />
	</ItemGroup>

</Project>
